apiVersion: v1
kind: ConfigMap
metadata:
  name: docbook-config
  namespace: docbook
data:
  MYSQL_DATABASE: "doctor_appointment_db"
  FRONTEND_URL: "http://localhost:3000"
  DEBUG: "true"
  APP_NAME: "DocBook - Doctor Appointment System"
  APP_VERSION: "1.0.0"
