apiVersion: v1
kind: Secret
metadata:
  name: docbook-secrets
  namespace: docbook
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123"
  SECRET_KEY: "your-super-secret-key-change-this-in-production"
  DATABASE_URL: "mysql+pymysql://root:root123@mysql-service.docbook.svc.cluster.local:3306/doctor_appointment_db"
